name: Save to GitHub
on:
  push:
    branches:
      - main
jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GTOKEN }}
          REPO_OWNER: ${{ secrets.OWNER }}
          REPO_NAME: ${{ secrets.GREP }}
        run: node sg.js
